services:
  - type: web
    name: youtube-downloader-bot-v2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /healthz
    envVars:
      - key: BOT_TOKEN
        sync: false
